config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'

  get '/profile', to: 'users#show', as: 'user_profile'

  resources :foundations, only: [:new, :create, :show, :index] do
    member do
      resources :pledges, only: [:new, :create, :cancel]
      resources :projects, only: [:new, :create, :show]
    end
  end

  resources :pledges, only: [:show]
end

app/models/pledge.rb
class Pledge < ApplicationRecord
  attr_accessor :bank_account
  attr_accessor :bank_routing

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :currency, presence: true

  has_many :payments
  belongs_to :user, inverse_of: :pledges
  belongs_to :foundation

  default_scope -> { order("created_at ASC") }
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  before_action :authenticate_user!

  def new
    @foundation = Foundation.find(params[:id])
    @pledge = Pledge.new
  end

  def create
    @foundation = Foundation.find(params[:id])
    @pledge = Pledge.new(
                amount: params[:amount],
                foundation_id: params[:id],
                user_id: current_user.id,
                currency: @foundation.local_currency
              )

    if @pledge.save
      if @foundation.deploy
        flash[:success] = "Congratulations! Your pledge was created and the foundation was deployed to the Ethereum blockchain. "
      end

      flash[:success] = "Your pledge has been created!"
      @foundation.activate
      redirect_to pledge_path(@pledge)
    end

  end

  def show
    @decorated_pledge = PledgeDecorator.new(Pledge.find(params[:id]))
  end

  def cancel
  end

  def pledge_params
    params.require(:pledge).permit(:amount)
  end
end

app/views/pledges/new.slim
.row
  .col.s12
    - if @foundation.pledges.empty?
      h4 Initial Pledge
    - else
      h4 New Pledge
.row
  .col.s12.m6
    - if @foundation.pledges.empty?
      p 
        | As the foundation proposer you must make the first pledge and provide additional funds to serve as 
          <strong>gas</strong> on the Ethereum network. Foundation funds are held in smart contracts on Ethereum and
          gas is required for contracts to run. This initial gas charge also helps us prevent abuse of this system.

    h6 How are funds held?
    p
      | Each foundation's funds are held securely and transparently in Ether in a smart contract wallet on the Ethereum blockchain.
        Fundo does not have access to your funds.

    h6 How are funds distributed to projects?
    p
      | Once the foundation activates, or if it is already active, all funders will receive <strong>Fundo tokens</strong> equal to the amount of your pledge.
        When your pledge is processed each month the smart contract will issue you additional tokens. Tokens can then be distributed to 
        project leaders, who can redeem them for funds from the foundation.
    
    h6 How often are pledges collected?
    p
      | To ensure solid cash flow for the foundation, pledges are collected monthly, converted to Ether and sent to the foundation's wallet. You can 
        cancel your pledge at any time.

    h6 What fees do you charge?
    p
      | Because Fundo takes advantage of the blockchain for storing funds we are able to drastically reduce overhead. However, to fund ongoing development
        and maintenance of this platform we retain <strong>1% of contributions</strong> as our fee. This is redeemed from the foundation wallet monthly based on the prior month's collected
        pledges.
  
  .col.s12.m6
    = form_with url: pledges_path, id: 'new-pledge' do |f|
      .row
        .col.s12
          h6 Pledge details
          .form-input
            = f.label :foundation, 'Foundation'
            = f.text_field :foundation, id: :pledge_foundation, value: @foundation.name, disabled: true 
          
          .form-input
            = f.label :currency, 'Foundation local currency'
            = f.text_field :currency, id: :pledge_currency, value: @foundation.local_currency, disabled: true

          - if @foundation.pledges.empty?
            .form-input
              = f.label :initial_gas, 'Initial gas'
              = f.text_field :initial_gas, id: :initial_gas, value: currency(Constants::INITIAL_GAS_USD), disabled: true
              .help-text A one-time charge to provide the foundation with funds to run on the Ethereum network.
          
          .form-input
            = f.label :amount, 'Monthly pledge amount'
            = f.text_field :amount, id: :pledge_amount
            .help-text Pledges denominated in the local currency of the foundation are collected each month and sent to the foundation's wallet

      .row
        .col.s12
          /* In a real version of the app, this would be replaced by Stripe or some other secure method of handling bank info */
          h6 Payment method
          .form-input
            = f.label :bank_account, 'Bank account number'
            = f.text_field :bank_account, id: :pledge_bank_account

          .form-input
            = f.label :bank_routing, 'Bank routing number'
            = f.text_field :bank_routing, id: :pledge_bank_routing

      .row
        .col.s12
          = button_tag 'Submit pledge', class: 'btn btn-large', id: 'submit-pledge', data: { disable_with: "Submitting..."}
      

app/views/pledges/show.slim
.row
  .col.s12.m6
    - if @decorated_pledge.is_initial_pledge?
      h4 Initial Pledge
    - else
      h4 Pledge
    span.muted= "ID: #{@decorated_pledge.pledge.id}"
.row
  .col.s12.m6
    p 
      - if @decorated_pledge.active?
        strong> This foundation is currently active.
      | Your pledge will be processed monthly on the 15th of the month.

    h6 Funder
    p= current_user.full_name
  
    h6 Foundation
    p= @decorated_pledge.pledge.foundation.name
    
    table
      thead
        th
          h6 Pledge details
        th.right
          h6= @decorated_pledge.pledge.currency
      tbody
        - if @decorated_pledge.is_initial_pledge?
          tr#initial-gas
            td
              span Inital gas fee (one-time charge)
            td.right
              span= "#{currency(Constants::INITIAL_GAS_USD)}"
        tr#pledge-amount
          td
            span Monthly pledge
          td.right
            span= "#{currency(@decorated_pledge.pledge.amount)}"
        - if @decorated_pledge.is_initial_pledge?
          tr#activation-amount
            td
              strong Total charged upon foundation activation
            td.right
              span= "#{currency(@decorated_pledge.total)}"
          tr#monthly-amount
            td
              strong Total charged each month
            td.right
              span= "#{currency(@decorated_pledge.pledge.amount)}"

    
.row
  .col.s12
    = link_to foundation_path(@decorated_pledge.pledge.foundation_id), class: 'btn btn-large', id: 'view-foundation'
      span View foundation