config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'

  get '/profile', to: 'users#show', as: 'user_profile'

  resources :foundations, only: [:new, :create, :show, :index] do
    member do
      resources :pledges, only: [:new, :create, :cancel]
      resources :projects, only: [:new, :create, :show]
    end
  end

  resources :pledges, only: [:show]
end

app/models/foundation.rb
class Foundation < ApplicationRecord
  geocoded_by :postal_code_and_country
  after_validation :geocode
  before_create :set_locality

  has_many :projects
  has_many :pledges
  has_many :payments
  has_many :eth_transactions
  has_many :token_transactions
  has_many :users, -> { distinct }, through: :pledges
  has_many :wallets, as: :walletable

  validates :country_alpha2, presence: true
  validates :local_currency, presence: true
  validates :postal_code, presence: true
  validates :min_starting_funds, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :min_participants, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :activation_deadline, presence: true
  validate :activation_deadline_must_be_in_future

  default_scope -> { order("created_at ASC") }

  def postal_code_and_country
    [postal_code, country_alpha2].join(' ')
  end

  def active?
    activated_on.present?
  end

  def activate
    if !active? && thresholds_met?
      self.update(activated_on: Time.now)
      Wallet.create(walletable: self, content_type: 'eth', foundation_id: id)
      Wallet.create(walletable: self, content_type: 'token', foundation_id: id)
      PaymentService.new(self).process_monthly
    end
  end

  def balance
    eth_transactions.sum(:amount).round(4)
  end

  def deploy
    EthereumService.new(self).deploy_contract
  end

  def name
    "Community Foundation of #{locality_name} (#{postal_code})"
  end

  def pledge_total
    pledges.sum(:amount).to_f
  end

  def status
    if activated_on.nil? && !thresholds_met? && activation_deadline <= Date.today
      "Expired"
    elsif activated_on.present?
      "Active"
    else
      "Pending"
    end
  end

  private

  def activation_deadline_must_be_in_future
    if activation_deadline.present? && activation_deadline < Date.today
      errors.add(:activation_date, 'must be in the future.')
    end
  end

  def thresholds_met?
    funding_threshold_met? && participant_threshold_met?
  end

  def funding_threshold_met?
    pledge_total >= min_starting_funds
  end

  def participant_threshold_met?
    users.size >= min_participants
  end

  def set_locality
    self.locality_name = GeocoderService.new(self.latitude, self.longitude).fetch_locality
  end
end

app/controllers/foundations_controller.rb
class FoundationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foundations = Foundation.all
  end

  def new
    country = get_user_country
    @user_country_code = country.alpha2
    @user_local_currency = country.currency_code
    @foundation = Foundation.new
  end

  def create
    @foundation = Foundation.new(foundation_params)
    if @foundation.save
      redirect_to new_pledge_path(@foundation.id)
    else
      render :new
    end
  end

  def show
    @foundation = Foundation.includes(:users).where(id: params[:id]).first
  end

  private

  def foundation_params
    params.require(:foundation).permit(:country_alpha2, :local_currency, :postal_code, :min_starting_funds, :min_participants, :activation_deadline)
  end

  def get_user_country
    location = set_location
    location.data["latitude"] = location.data["loc"].split(',')[0] unless location.data["latitude"].present?
    location.data["longitude"] = location.data["loc"].split(',')[1] unless location.data["longitude"].present?
    user_location = Geocoder.search("#{location.data["latitude"]},#{location.data["longitude"]}").first
    @user_country ||= ISO3166::Country.find_country_by_name(user_location.country)
  end
end

app/views/foundations/index.slim
.row
  .col.s12
    h4 Join a foundation

    p.flow-text
      | Community philanthropy is important for developing civil society and making the world
        around you better. Join a foundation today and start contributing to projects in your neighborhood.
    p.flow-text Don't see your neighborhood?
    = link_to new_foundation_path, class: 'btn btn-large', id: 'create-foundation'
      i.material-icons.left add_circle_outline
      | Create foundation

.row
  .col.s12
    h4 Current foundations
    - if @foundations.any?

      ul.collection
        - @foundations.each do |foundation|
          li.collection-item.avatar
            i.material-icons.circle.pink place
            strong= link_to foundation.name, foundation_path(foundation)
            p.muted
              span= "#{foundation.status} | "
              span= "#{foundation.users.count} funders | "
              span= "#{currency(foundation.pledge_total)} #{foundation.local_currency} per month pledged"
    - else
      p No foundations yet :(

app/views/foundations/new.slim
.row
  .col.s12
    h3 Create a foundation for your community

    p.flow-text
      | Complete the information below to deploy your foundation to the Ethereum blockchain. 
        Once your foundations achieves the thresholds you define for minimum participants and minimum funds, 
        it will activate and disburse local currency token to all contributors in recognition of their contribution.

.row
  = form_with model: @foundation do |f|
    .row
      .col.s12.m6
        = f.label :country_alpha2, 'Country'
        = f.country_select :country_alpha2, { selected: @user_country_code }, { id: 'foundation_country_alpha2' }
      .col.s12.m6
        = f.label :local_currency, 'Local currency'
        = f.text_field :local_currency, id: :foundation_local_currency, value: @user_local_currency 
    .row
      .col.s12.m6
        = f.label :postal_code, 'Postal code'
        = f.text_field :postal_code, id: :foundation_postal_code
        .help-text What local community will the foundation serve?
      .col.s12.m6
        = f.label :min_starting_funds
          span Minimum starting funds
        = f.text_field :min_starting_funds, id: :foundation_min_starting_funds
        .help-text How much must be pledged by all participants for the foundation to activate?
    .row
      .col.s12.m6
        = f.label :min_participants
          span Minimum participants
        = f.text_field :min_participants, id: :foundation_min_participants
        .help-text How many contributors are required for the foundation to activate?
      .col.s12.m6
        = f.label :activation_deadline, 'Activation deadline'
        = f.text_field :activation_deadline, id: :foundation_activation_deadline, class: 'datepicker'
        .help-text If the foundation doesn't activate by this date, it will expire
    = button_tag 'Create', class: 'btn-large pink', id: 'create', data: { disable_with: "Creating..."}
    

app/views/foundations/show.slim
= tag.div nil, id:'map', class: 'col s12 m8 foundation-map', data: { location: @foundation }
.row
  .col.s12
    .foundation-container
      h3= @foundation.name
      p.help-text
        span> Ethereum blockchain address:
        span= @foundation.address
      .row
        #tabs.col.s12.m7.l8
          .row
            .col.s12
              ul.tabs
                li.tab.col.s3
                  =link_to 'Funders', '#funders', id: 'funders-link'
                li.tab.col.s3
                  =link_to 'Projects', '#projects', id: 'projects-link'
                li.tab.col.s3
                  =link_to 'Activity', '#activity', id: 'activity-link'

            #funders.col.s12
              - if @foundation.pledges.any?
                ul.collection
                  - @foundation.pledges.each do |pledge|
                    li.collection-item.avatar
                      i.material-icons.circle.pink face
                      strong.title= pledge.user.full_name
                      p= "Joined on #{pledge.created_at.strftime('%e %B, %Y')}"
                      
              - else
                p No contributors yet :(

            #projects.col.s12
              - if @foundation.projects.any?
                .row
                  - @foundation.projects.each do |project|
                    .col.s12.m6
                      .card.pink
                        .card-content.white-text
                          span.card-title= project.title
                          p= project.short_description
                        .card-action
                          =link_to 'More info', project_path(project)

              - else
                p No projects yet :(
              = link_to new_project_path, class: 'btn btn-large', id: 'create-foundation'
                i.material-icons.left add_circle_outline
                | Create project

            #activity.col.s12
              - if @foundation.eth_transactions.any?
                ul.collection
                  - @foundation.eth_transactions.each do |t|
                    li.collection-item.avatar
                      i.material-icons.circle.pink flash_on
                      strong.title
                        span> Ether
                        span= t.amount > 0 ? "Deposit" : "Withdrawal"
                      p.muted
                        = "#{t.id}"
                        br
                        = "#{t.amount.round(9)} on #{t.created_at.strftime('%e %B, %Y')} | "
              - else
                p No activity yet :(

        #stats.col.s12.m5.l4
          
          - if !@foundation.users.include?(current_user) && @foundation.status != "Expired"
            .col.s12
              = link_to new_pledge_path(@foundation), class: 'btn btn-large', id: 'new-pledge-link'
                i.material-icons.left favorite_border
                | Join foundation
          .col.s12
            #status.card
              .card-content
                span.card-title Status
                h4= @foundation.status
                - if @foundation.active?
                  p.help-text= "Foundation activated on <strong>#{@foundation.activated_on.strftime('%e %B, %Y')}</strong>.".html_safe
                - elsif @foundation.status == "Expired"
                  p.help-text= "Foundation was not activated because the required participation thresholds were not met by <strong>#{@foundation.activation_deadline.strftime('%e %B, %Y')}</strong>.".html_safe
                - else
                  p.help-text= "Foundation will activate on <strong>#{@foundation.activation_deadline.strftime('%e %B, %Y')}</strong> if the funding and participation thresholds are met.".html_safe

          .col.s12
            #balance.card
              .card-content
                span.card-title Balance
                h4= @foundation.balance
                p.help-text Funds are held in Ether (ETH). Current exchange rate is $304.59 USD/ETH
          .col.s12
            #funders-total.card
              .card-content
                span.card-title Funders
                h4= @foundation.users.size
                - if @foundation.active?
                  p.help-text= "#{@foundation.users.size} people are supporting this foundation"
                -else
                  p.help-text= "#{@foundation.min_participants} funders required in order to activate"
          .col.s12
            .card
              #pledges-total.card-content
                span.card-title Total Pledges
                h4= "#{currency(@foundation.pledge_total)} #{@foundation.local_currency}"
                - if @foundation.active?
                  p.help-text Total amount contributed per month from all funders.
                - else
                  p.help-text= "#{number_with_precision(@foundation.min_starting_funds, delimiter: ",", precision: 2)} #{@foundation.local_currency} required in order to activate"