config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users, controllers: { registrations: 'registrations' }
  root 'home#index'

  get '/profile', to: 'users#show', as: 'user_profile'

  resources :foundations, only: [:new, :create, :show, :index] do
    member do
      resources :pledges, only: [:new, :create, :cancel]
      resources :projects, only: [:new, :create, :show]
    end
  end

  resources :pledges, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pledges
  has_many :foundation, -> { distinct }, through: :pledges
  has_many :wallets, as: :walletable
  has_many :projects

  default_scope -> { order("created_at ASC") }

  def token_balance(foundation)
    binding.pry
    received_token_transactions.sum(:amount) - sent_token_transactions.sum(:amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @pledges = Pledge.includes(:foundation).where(user_id: current_user.id)
    @wallets = current_user.wallets
  end
end

app/views/users/show.slim
.row
  .col.s12.m4.offset-m4
    .avatar.center
      i.material-icons.circle.pink.large.white-text face
.row
  .col.s12
    h4.center= current_user.full_name

.row
  #tabs.col.s12
    .row
      .col.s12
        ul.tabs
          li.tab.col.s3
            =link_to 'My Info', '#info', id: 'info-link'
          li.tab.col.s3
            =link_to 'Pledges', '#pledges', id: 'pledges-link', class: 'active'
          li.tab.col.s3
            =link_to 'Wallets', '#wallets', id: 'wallets-link'
      
        #info.col.s12
          p User info goes here

        #pledges.col.s12
          - if @pledges.any?
            ul.collection
              - @pledges.each do |pledge|
                li.collection-item.avatar
                  i.material-icons.circle.pink favorite
                  strong= link_to pledge.foundation.name, pledge_path(pledge)
                  p.muted
                    span= "#{currency(pledge.amount)} per month | "
                    span= "Pledge created on #{pledge.created_at.strftime('%e %B, %Y')}"
          - else
            p No pledges yet.
            = link_to foundations_path, class: 'btn btn-large', id: 'join-foundation'
              span Join foundation

        #wallets.col.s12
          - if @wallets.any?
            ul.collection
              - @wallets.each do |wallet|
                li.collection-item.avatar
                  i.material-icons.circle.pink lock
                  strong= "#{Foundation.where(id: wallet.foundation_id).first.name}"
                  p.muted
                    span= "#{wallet.balance} foundation tokens"
          - else
            p No wallets yet.
            = link_to foundations_path, class: 'btn btn-large', id: 'join-foundation'
              span Join foundation